/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AceEditor: typeof import('./src/components/AceEditor.vue')['default']
    ActionCableStatus: typeof import('./src/components/ActionCableStatus.vue')['default']
    AuditLogsTab: typeof import('./src/components/admin/AuditLogsTab.vue')['default']
    AutomationRuleDialog: typeof import('./src/views/_dialogs/AutomationRuleDialog.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    ConditionEditDialog: typeof import('./src/views/_dialogs/ConditionEditDialog.vue')['default']
    ConditionGroupDisplay: typeof import('./src/components/project/ConditionGroupDisplay.vue')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    FlowEdit: typeof import('./src/components/flow-edit.vue')['default']
    GaIcon: typeof import('./src/components/icon/ga-icon.vue')['default']
    GitHubLogin: typeof import('./src/components/GitHubLogin.vue')['default']
    HostConfigSetting: typeof import('./src/components/node-setting/HostConfigSetting.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Panel: typeof import('primevue/panel')['default']
    Password: typeof import('primevue/password')['default']
    PermissionManagementTab: typeof import('./src/components/admin/PermissionManagementTab.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RoleManagementTab: typeof import('./src/components/admin/RoleManagementTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingColumn: typeof import('./src/components/node-setting/SettingColumn.vue')['default']
    SqlEditor: typeof import('./src/components/SqlEditor.vue')['default']
    SystemStatsTab: typeof import('./src/components/admin/SystemStatsTab.vue')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    Tag: typeof import('primevue/tag')['default']
    TaskExecutionStats: typeof import('./src/components/TaskExecutionStats.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    UploadCosSetting: typeof import('./src/components/node-setting/UploadCosSetting.vue')['default']
    UserManagementTab: typeof import('./src/components/admin/UserManagementTab.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
